version: "3.6"
services:
  product-service:
    image: "my-registry.com/jami/quarkus/product-service"
    depends_on:
      - mongo
      - keycloak
    ports:
      - 8080:8080
  mongo:
    image: "mongo:4.4.6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  keycloak:
    image: "quay.io/keycloak/keycloak:13.0.0"
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
